"""empty message

Revision ID: efee52503b6c
Revises: 
Create Date: 2021-08-03 01:49:35.414890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efee52503b6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(length=100), nullable=True),
    sa.Column('admin_password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('img_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pname', sa.String(length=100), nullable=True),
    sa.Column('raddress', sa.String(length=100), nullable=True),
    sa.Column('oaddress', sa.String(length=100), nullable=True),
    sa.Column('tel', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('etel', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siblings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.String(length=100), nullable=True),
    sa.Column('s_class_', sa.String(length=100), nullable=True),
    sa.Column('s_year', sa.String(length=100), nullable=True),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentid'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sname', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.String(length=100), nullable=True),
    sa.Column('bg', sa.String(length=100), nullable=True),
    sa.Column('bp', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('gen', sa.String(length=50), nullable=True),
    sa.Column('lga', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('ail', sa.String(length=10), nullable=True),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('school_address', sa.String(length=200), nullable=True),
    sa.Column('class_', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=100), nullable=True),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentid'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_name', sa.String(length=100), nullable=True),
    sa.Column('sub_email', sa.String(length=100), nullable=True),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentid'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber')
    op.drop_table('student')
    op.drop_table('siblings')
    op.drop_table('parent')
    op.drop_table('news')
    op.drop_table('admin')
    # ### end Alembic commands ###
